### ISSUE TITLE
unrecognized arguments: --filetype jpg

### ISSUE THREAD

**Issue by Ianmcmill** [sleepy-maker/easyGAN#9]
Missing args parser?

> easygan --folder "256x512" --batch 32 --filetype jpg
> Using TensorFlow backend.
> usage: easygan [-h] [-s SEARCH] [-k KEYWORD] [-f FOLDER] [-ff FILEFORMAT]
>                [-b BATCH]
> easygan: error: _unrecognized arguments: --filetype jpg

But `-ff jpg` works.

**Comment by sleepy-maker** [comment]
@Ianmcmill thank you for reporting this!
Will fix this.

**Comment by sleepy-maker** [comment]
not `--filetype` but `--fileformat`
